version: "3.9"
services: 
    api:
        image: nefcanto/dotnet-dev
        container_name: ${Package}DotNetApi
        working_dir: /api
        environment: 
            - HolismProjectsRoot=/HolismDotNet
        volumes: 
            - /HolismDotNet/Framework:/HolismDotNet/Framework
            - /HolismDotNet/Api:/HolismDotNet/Api
            - .:/api
        ports: 
            - "5000:5000"
        command: >
            sh -c
            "
            cd /temp
            && tail -f /dev/null
            "