version: "3.9"
services: 
    api:
        image: nefcanto/dotnet-dev:latest
        restart: always
        container_name: ${Package}DotNetApi
        working_dir: /Api
        environment: 
            - HolismProjectsRoot=/HolismDotNet
        volumes: 
            - /HolismDotNet/Framework:/HolismDotNet/Framework
            - /HolismDotNet/Api:/HolismDotNet/Api
            - .:/Api
        ports: 
            - "5000:5000"
        command: >
            sh -c
            "
            dotnet build
            && dotnet Api/bin/Holism.${Package}.Api.dll
            "
        depends_on: 
            - "sql"
    sql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: always
        container_name: ${Package}Sql
        volumes:
            - ./Database:/var/opt/mssql
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=lksU2o412f7tBj58t07B
            - MSSQL_PID=Express
        ports:
            - 1433:1433
        command: >
            sh -c
            "
            tail -f /dev/null
            "